<?php
namespace Exchanges\Exchanges\Coinbase;
use Exchanges\DTOs\{TickerDTO,OrderBookDTO,OrderDTO,TradeDTO,BalanceDTO,CandleDTO,DepositDTO,WithdrawDTO,ExchangeInfoDTO};
class CoinbaseNormalizer
{
    public function ticker(array $d): TickerDTO { return new TickerDTO(symbol:$d['product_id'],price:(float)($d['price']??$d['close']??0),bid:(float)($d['best_bid']??0),ask:(float)($d['best_ask']??0),open24h:(float)($d['open_24h']??0),high24h:(float)($d['high_52w']??$d['high_24h']??0),low24h:(float)($d['low_52w']??$d['low_24h']??0),volume24h:(float)($d['volume_24h']??0),quoteVolume24h:(float)($d['quote_volume_24h']??0),change24h:(float)($d['price_percentage_change_24h']??0)*(float)($d['price']??1)/100,changePct24h:(float)($d['price_percentage_change_24h']??0),timestamp:time()*1000,exchange:'coinbase'); }
    public function orderBook(string $symbol, array $d): OrderBookDTO { $p=$d['pricebook']??$d; return new OrderBookDTO(symbol:$symbol,bids:array_map(fn($b)=>[(float)$b['price'],(float)$b['size']],$p['bids']??[]),asks:array_map(fn($a)=>[(float)$a['price'],(float)$a['size']],$p['asks']??[]),timestamp:time()*1000,exchange:'coinbase'); }
    public function order(array $d): OrderDTO { $o=$d['order']??$d; $c=$o['order_configuration']??[]; $lc=$c['limit_limit_gtc']??$c['market_market_ioc']??[]; $sm=['OPEN'=>OrderDTO::STATUS_OPEN,'FILLED'=>OrderDTO::STATUS_FILLED,'CANCELLED'=>OrderDTO::STATUS_CANCELLED,'EXPIRED'=>OrderDTO::STATUS_EXPIRED,'PENDING'=>OrderDTO::STATUS_OPEN]; return new OrderDTO(orderId:$o['order_id']??'',clientOrderId:$o['client_order_id']??'',symbol:$o['product_id']??'',side:$o['side']??'BUY',type:strtoupper(array_key_first($c)??'LIMIT'),status:$sm[$o['status']]??OrderDTO::STATUS_OPEN,quantity:(float)($o['base_size']??$lc['base_size']??0),executedQty:(float)($o['filled_size']??0),price:(float)($lc['limit_price']??0),avgPrice:(float)($o['average_filled_price']??0),stopPrice:0,timeInForce:'GTC',fee:(float)($o['total_fees']??0),feeAsset:'',createdAt:isset($o['created_time'])?strtotime($o['created_time'])*1000:time()*1000,updatedAt:time()*1000,exchange:'coinbase'); }
    public function balance(string $asset, array $d): BalanceDTO { $v=$d['available_balance']??[]; return new BalanceDTO(asset:$asset,free:(float)($v['value']??0),locked:0,staked:0,exchange:'coinbase'); }
    public function candle(string $symbol, string $interval, array $d): CandleDTO { return new CandleDTO(symbol:$symbol,interval:$interval,openTime:(int)($d['start']??0)*1000,open:(float)($d['open']??0),high:(float)($d['high']??0),low:(float)($d['low']??0),close:(float)($d['close']??0),volume:(float)($d['volume']??0),quoteVolume:0,trades:0,closeTime:(int)($d['start']??0)*1000+3600000,exchange:'coinbase'); }
    public function depositAddress(string $asset, array $d): DepositDTO { return new DepositDTO(asset:$asset,address:$d['deposit_uri']??$d['address']??'',memo:null,network:$d['network']??'',depositId:null,amount:null,txId:null,status:DepositDTO::STATUS_CONFIRMED,timestamp:null,exchange:'coinbase'); }
    public function withdraw(array $d): WithdrawDTO { $a=(float)($d['amount']??0);$f=(float)($d['fee']??0); return new WithdrawDTO(withdrawId:$d['id']??'',asset:$d['currency']??'',address:$d['crypto_address']??'',memo:null,network:'',amount:$a,fee:$f,netAmount:$a-$f,txId:$d['network']??null,status:WithdrawDTO::STATUS_PENDING,timestamp:time()*1000,exchange:'coinbase'); }
}
